Demo.ASP/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Models
{
    public class Contact
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public DateTime BirthDate { get; set; }
    }
}

Demo.ASP/Models/ErrorViewModel.cs
using System;

namespace Demo.ASP.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demo.ASP/Models/Forms/BmiForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Models.Forms
{
    public class BmiForm
    {
        [Required(ErrorMessage = "Ce champs est requis")]
        [Range(0, 300, ErrorMessage = "Taille non valide")]
        public int Taille { get; set; } // cm

        [Required]
        [Range(0, 1000)]
        public int Poids { get; set; } // kg

        public float Bmi 
        { 
            get { return Poids / (Taille * Taille / 10000f); } 
        }
    }
}

Demo.ASP/Models/Forms/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Models.Forms
{
    public class ContactForm
    {
        [Required]
        [MinLength(2)]
        [MaxLength(100)]
        public string Subject { get; set; }
        
        
        [Required]
        [MaxLength(1000)]
        public string Content { get; set; }
    }
}

Demo.ASP/Models/Forms/TableForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Models.Forms
{
    public class TableForm
    {
        public int NbTables { get; set; }
        public int StartTable { get; set; }
    }
}

Demo.ASP/Controllers/CalculController.cs
using Demo.ASP.Models.Forms;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Controllers
{
    public class CalculController : Controller
    {
        // affichage du formulaire
        public IActionResult Formulaire()
        {
            return View();
        }

        // traitement du forulaire
        [HttpPost]
        public IActionResult Formulaire([FromForm]TableForm body)
        {
            return View(body);
        }
    }
}

Demo.ASP/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Demo.ASP/Controllers/ExerciceController.cs
using Demo.ASP.Models.Forms;
using Demo.ASP.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;

namespace Demo.ASP.Controllers
{
    public class ExerciceController : Controller
    {
        public IActionResult Bmi()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Bmi([FromForm] BmiForm form)
        {
            if(ModelState.IsValid) // vérifier la validité du forumulaire
            {
                // faire action ...
                return View(form);
            }
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Contact([FromForm] ContactForm form)
        {
            if(ModelState.IsValid)
            {
                // envoyer un email

                if(!(new MailService()).SendEmail(form.Subject, form.Content, "lykhun@gmail.com"))
                {
                    TempData["error_message"] = "Une erreur est survenue";
                    // rester sur la page
                    return View(form);
                }

                // afficher une message
                TempData["success_message"] = "Le message a bien été envoyé";
                // rediriger autre part
                return RedirectToAction("Index", "Home");
            }
            // afficher un message d'erreur
            TempData["error_message"] = "Une erreur est survenue";
            // rester sur la page
            return View(form);
        }
    }
}

Demo.ASP/Controllers/HomeController.cs
using Demo.ASP.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Demo.ASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demo.ASP/Views/Calcul/Formulaire.cshtml
@*indication qui détermine le TYPE du model*@
@model Demo.ASP.Models.Forms.TableForm

<form class="form" asp-controller="Calcul" asp-action="Formulaire" method="post">
    <div class="mb-2">
        <label>Nb de tables souhaitées</label>
        <input name="NbTables" class="form-control" type="number">
    </div>
    <div class="mb-2">
        <label>Table de départ</label>
        <input name="StartTable" class="form-control" type="number">
    </div>
    <div class="mb-2">
        <button class="btn btn-outline-danger">Envoyer</button>
    </div>
</form>
@if(Model != null)
{
    <p>Nb Tables = @Model.NbTables</p>
    <p>Table de départ = @Model.StartTable</p>

    @for(int table=Model.StartTable; table<Model.NbTables+Model.StartTable; table++)
    {
        <h1>Table de @table</h1>
        for(int multiplicateur=1; multiplicateur <= 10; multiplicateur++)
        {
            <p>@table X @multiplicateur = @(table * multiplicateur)</p>
        }
    }
}

Demo.ASP/Views/Contact/Index.cshtml
@* commentaire *@

@{
    // code c#
    int nb = 42;
    Contact c = new Contact
    {
        Id = 1,
        LastName = "Ly",
        FirstName = "Khun",
        BirthDate = new DateTime(1982, 5, 6)
    };
}

@* @nb ou @(nb) => afficher la variable nb *@
<p>le nombre @nb multiplié par 2 = @(nb * 2) </p>
<p>email: @@gmail.com </p>




@if(nb > 30) {
    <p>le nombre est plus grand que 30</p>
}
else {
    <p>le nombre est plus petit ou égal à 30</p>
}

@while(nb > 0) {
    <p>@nb</p>
    nb--;
}

<div>
    <p>Nom : @c.LastName</p>
    <p>Prénom: @c.FirstName</p>
    <p>Date de naissance : @c.BirthDate</p>
</div> 

Demo.ASP/Views/Exercice/Bmi.cshtml
@model Demo.ASP.Models.Forms.BmiForm

<form method="post">
    <div>
        <input name="Taille" class="form-control mb-2" type="number" placeholder="Taille">
        <span class="text-danger" asp-validation-for="Taille"></span>
        @* afficher les messages d'erreurs *@
    </div>
    <div>
        <input name="Poids" class="form-control mb-2" type="number" placeholder="Poids">
        <span class="text-danger" asp-validation-for="Poids"></span>
    </div>
    <button class="btn btn-outline-secondary">Calculer BMI</button>
</form>

@if(Model != null)
{
    // afficher le résulat
    <p>BMI : @Model.Bmi</p>
    @if(@Model.Bmi < 18.5)
    {
        <p>Vous avez un poids insuffisant</p>
    }
    else if(@Model.Bmi < 25)
    {
        <p>Vous avez un poids normal</p>
    }
    else if(@Model.Bmi < 30)
    {
        <p>Vous êtes en surpoids</p>
    }
    else if(@Model.Bmi < 40)
    {
        <p>Vous êtes en obèse</p>
    }
    else
    {
        <p>Vous êtes en obèse morbide</p>
    }
}

Demo.ASP/Views/Exercice/Contact.cshtml
@model Demo.ASP.Models.Forms.ContactForm

@{
    ViewData["Title"] = "Contact";
}

<h1>Contact</h1>

<h4>ContactForm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Contact">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Subject" class="control-label"></label>
                <input asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label"></label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@*
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}*@

Demo.ASP/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Khun LY</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Demo.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Demo.ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Demo.ASP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if(TempData["success_message"] != null)
            {
                <div class="alert alert-success">
                    @TempData["success_message"]
                </div>
            }
            @if(TempData["error_message"] != null)
            {
                <div class="alert alert-danger">
                    @TempData["error_message"]
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Demo.ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @if(TempData["success_message"] != null)
    {
        <script>
            toastr.success('@TempData["success_message"]');
        </script>
    }
    @if(TempData["error_message"] != null)
    {
        <script>
            toastr.error('@TempData["error_message"]');
        </script>
    }
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>